data = [

    {
        id: 0,
        name: 'Jonny and the T-Tops',
        city: 'Las Vegas',
        state: 'NV',
        genre: 'Rockabilly',
        solo: 0,
        account_id: 0,
        birthdate: 1998,
        image_url: 'https://i.imgur.com/jyBYHt5.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        bandcamp_url: 'http://www.bandcamp.com',
        spotify_url: 'http://www.spotify.com',
        facebook_url: 'http://www.facebook.com',
        homepage_url: 'http://www.google.com',
        contact_email: 'jonny@gmail.com',
        contact_num: 5551234567,
        contact_facebook: 'http://www.facebook.com'
    },
    {
        id: 1,
        name: 'Robert Barron',
        city: 'New Orleans',
        Stae: 'LA',
        genre: 'hip-hop',
        solo: 1,
        account_id: 1,
        birthdate: 1996,
        image_url: 'https://i.imgur.com/lWAlvwF.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        bandcamp_url: 'http://www.bandcamp.com',
        spotify_url: 'http://www.spotify.com',
        facebook_url: 'http://www.facebook.com',
        homepage_url: 'http://www.google.com',
        contact_email: 'bobby@gmail.com',
        contact_num: 5551239090,
        contact_facebook: 'http://www.facebook.com'
    },
    {
        id: 2,
        name: 'Kelly Harris',
        city: 'Dallas',
        state: 'TX',
        genre: 'Singer Songwriter',
        solo: 1,
        account_id: 2,
        birthdate: 1998,
        image_url: 'https://i.imgur.com/YyWVudy.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        bandcamp_url: 'http://www.bandcamp.com',
        spotify_url: 'http://www.spotify.com',
        facebook_url: 'http://www.facebook.com',
        homepage_url: 'http://www.google.com',
        contact_email: 'kellyh@gmail.com',
        contact_num: 5551231111,
        contact_facebook: 'http://www.facebook.com'
    },
    {
        id: 3,
        name: 'Mick Gagger and the Bones',
        city: 'Athens',
        state: 'GA',
        genre: 'punk',
        solo: 0,
        account_id: 3,
        birthdate: 2010,
        image_url: 'https://i.imgur.com/pmKJNV8.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        bandcamp_url: 'http://www.bandcamp.com',
        spotify_url: 'http://www.spotify.com',
        facebook_url: 'http://www.facebook.com',
        homepage_url: 'http://www.google.com',
        contact_email: 'kellyh@gmail.com',
        contact_num: 5551231111,
        contact_facebook: 'http://www.facebook.com'
    },
    {
        id: 4,
        name: 'Breeeze',
        city: 'Brooklyn',
        state: 'NY',
        genre: 'chillwave',
        solo: 0,
        account_id: 4,
        birthdate: 2012,
        image_url: 'https://i.imgur.com/WRB0gBu.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        bandcamp_url: 'http://www.bandcamp.com',
        spotify_url: 'http://www.spotify.com',
        facebook_url: 'http://www.facebook.com',
        homepage_url: 'http://www.google.com',
        contact_email: 'kellyh@gmail.com',
        contact_num: 5551231111,
        contact_facebook: 'http://www.facebook.com'
    },
]
module.exports.data = data;