const data = [
    {
        id: 0,
        title: 'Singer/Songwriter night' ,
        date: '2019-06-22 20:30:00',
        artist_id: 2,
        description: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis ',
        venue: 'The Purple Cat',
        type: 'looking for bands',
        image_url: 'https://i.imgur.com/75ElGIl.jpg',
    },
    {
        id: 1,
        title: 'Shock and Awesome',
        date: '2019-05-18 22:00:00' ,
        artist_id: 3,
        description: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis ',
        venue: 'Passed Out Lounge',
        type: 'gig looking for bands',
        image_url: 'https://i.imgur.com/NQDMg5r.jpg',
    },
    {
        id: 2,
        title: '4:20 Eve',
        date: '2019-04-19 18:00:00' ,
        artist_id: 4,
        description: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis ',
        venue: 'Sylverlyte',
        type: 'band looking for opener',
        image_url: 'https://i.imgur.com/cB6g6XR.jpg',
    },
    {
        id: 3,
        title: 'Barron All Tour 2019',
        date: '2019-06-03 21:00:00' ,
        artist_id: 1,
        description: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis ',
        venue: 'Warehouse 42',
        type: 'artist looking for opener',
        image_url: 'https://i.imgur.com/Auy9lIc.jpg',
    },
    {
        id: 4,
        title: `Lil Momma's Swingin' BBQ cookcoff ` ,
        date: '2019-07-05 02:30:00' ,
        artist_id: 0,
        description: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis ',
        venue: 'Westin Park',
        type: 'band looking for more bands',
        image_url: 'https://i.imgur.com/QinTXqG.jpg',
    },
]

module.exports = data;