const data = [
    {
        id: 0,
        title: 'Singer/Songwriter night' ,
        date: '2019-06-22 20:30:00',
        description: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis ',
        venue: 'The Purple Cat',
        type: 'open mic',
        urlImage: 'https://i.imgur.com/75ElGIl.jpg',
        idBand: null,
        idMusician: 0,
    },
    {
        id: 1,
        title: 'Shock and Awesome',
        date: '2019-05-18 22:00:00' ,
        description: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis ',
        venue: 'Passed Out Lounge',
        type: 'gig',
        urlImage: 'https://i.imgur.com/NQDMg5r.jpg',
        idBand: 1,
        idMusician: null,
    },
    {
        id: 2,
        title: '4:20 Eve',
        date: '2019-04-19 18:00:00' ,
        description: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis ',
        venue: 'Sylverlyte',
        type: 'gig',
        urlImage: 'https://i.imgur.com/cB6g6XR.jpg',
        idBand: 2,
        idMusician: null,
    },
    {
        id: 3,
        title: 'Barron All Tour 2019',
        date: '2019-06-03 21:00:00' ,
        description: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis ',
        venue: 'Warehouse 42',
        type: 'opening act',
        urlImage: 'https://i.imgur.com/Auy9lIc.jpg',
        idBand: null,
        idMusician: 1,
    },
    {
        id: 4,
        title: `Lil Momma's Swingin' BBQ cookcoff ` ,
        date: '2019-07-05 02:30:00' ,
        description: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis ',
        venue: 'Westin Park',
        type: 'outdoor festival',
        urlImage: 'https://i.imgur.com/QinTXqG.jpg',
        idBand: 0,
        idMusician: null,
    },
]