const data = [
    {
        id: 0,
        url: 'https://i.imgur.com/jyBYHt5.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        url_bandcamp: 'http://www.bandcamp.com',
        url_spotify: 'http://www.spotify.com',
        url_facebook:'http://www.facebook.com',
        url_homepage:'http://www.google.com',
        band_id: 0,
        musician_id: null,
    },
    {
        id: 1,
        url: 'https://i.imgur.com/lWAlvwF.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        url_bandcamp: 'http://www.bandcamp.com',
        url_spotify: 'http://www.spotify.com',
        url_facebook: 'http://www.facebook.com',
        url_homepage: 'http://www.google.com',
        band_id: null,
        musician_id: 1,
    },
    {
        id: 2,
        url: 'https://i.imgur.com/YyWVudy.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        url_bandcamp: 'http://www.bandcamp.com',
        url_spotify: 'http://www.spotify.com',
        url_facebook: 'http://www.facebook.com',
        url_homepage: 'http://www.google.com',
        band_id: null,
        musician_id: 0,
    },
    {
        id: 3,
        url: 'https://i.imgur.com/pmKJNV8.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        url_bandcamp: 'http://www.bandcamp.com',
        url_spotify: 'http://www.spotify.com',
        url_facebook: 'http://www.facebook.com',
        url_homepage: 'http://www.google.com',
        band_id: 1,
        musician_id: null,
    },
    {
        id: 4,
        url: 'https://i.imgur.com/WRB0gBu.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        url_bandcamp: 'http://www.bandcamp.com',
        url_spotify: 'http://www.spotify.com',
        url_facebook: 'http://www.facebook.com',
        url_homepage: 'http://www.google.com',
        band_id: 2,
        musician_id: null,
    },
]
module.exports.data = data;