const data = [
    {
        id: 0,
        url: 'https://i.imgur.com/jyBYHt5.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        urlBandcamp: 'http://www.bandcamp.com',
        urlSpotify: 'http://www.spotify.com',
        urlFacebook:'http://www.facebook.com',
        urlHomepage:'http://www.google.com',
        idBand: 0,
        idMusician: null,
    },
    {
        id: 1,
        url: 'https://i.imgur.com/lWAlvwF.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        urlBandcamp: 'http://www.bandcamp.com',
        urlSpotify: 'http://www.spotify.com',
        urlFacebook: 'http://www.facebook.com',
        urlHomepage: 'http://www.google.com',
        idBand: null,
        idMusician: 1,
    },
    {
        id: 2,
        url: 'https://i.imgur.com/YyWVudy.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        urlBandcamp: 'http://www.bandcamp.com',
        urlSpotify: 'http://www.spotify.com',
        urlFacebook: 'http://www.facebook.com',
        urlHomepage: 'http://www.google.com',
        idBand: null,
        idMusician: 0,
    },
    {
        id: 3,
        url: 'https://i.imgur.com/pmKJNV8.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        urlBandcamp: 'http://www.bandcamp.com',
        urlSpotify: 'http://www.spotify.com',
        urlFacebook: 'http://www.facebook.com',
        urlHomepage: 'http://www.google.com',
        idBand: 1,
        idMusician: null,
    },
    {
        id: 4,
        url: 'https://i.imgur.com/WRB0gBu.jpg',
        bio: 'ut ornare lectus sit amet est placerat in egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor id eu nisl nunc mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget felis',
        urlBandcamp: 'http://www.bandcamp.com',
        urlSpotify: 'http://www.spotify.com',
        urlFacebook: 'http://www.facebook.com',
        urlHomepage: 'http://www.google.com',
        idBand: 2,
        idMusician: null,
    },
]
module.exports.data = data;